# Site settings
title: Greg Blog
email: harrison.greg.c@gmail.com
description:
  Hello! 
  This is a place where I write about concepts that I come across in my work as a Web Developer.
  I hope you find it interesting!
  #  this means to ignore newlines until "baseurl:"
  #  Write an awesome description for your new site here. You can edit this
  #  line in _config.yml. It will appear in your document head meta (for
  #  Google search results) and in your feed.xml site description.
baseurl: "/greg-blog" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: 8bt_g
github_username:  greg-harrison

# Build settings
markdown: redcarpet
